# Generated by Django 2.2.6 on 2019-10-19 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=50)),
                ('govt_id', models.IntegerField(default=0)),
                ('number_of_guest', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Room_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classic', models.BooleanField(default=False)),
                ('delux', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.Room_type')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('room_nu', models.IntegerField(primary_key=True, serialize=False)),
                ('add_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.Room_type')),
                ('guest_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.Guest')),
                ('room_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.IntegerField()),
                ('check_in_date', models.DateTimeField()),
                ('check_out_date', models.DateTimeField()),
                ('cancel', models.BooleanField(default=False)),
                ('Complete', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.Manager')),
            ],
        ),
    ]
